### ISSUE TITLE
Dieing without an error

### ISSUE THREAD

**Issue by puggan** [jgable/gulp-cache#73]
Set up an exemple project, to see why gulp-typescript, gulp-cache didn't work togheter. 
https://github.com/puggan/exemples/tree/bug/gulp-typescript

As both the tasks "ts1-cache" and "map-cache" fails / dies without an error,
my guess is that its something wrong in the gulp-cache package.

**Comment by dangreen** [comment]
@puggan What with https://github.com/jgable/gulp-cache/releases/tag/v1.1.1 ?

**Comment by huochunpeng** [comment]
I tried gulp-cache with gulp-typescript before, they don't work well.
gulp-typescript is not doing things in "gulp" way, I also had issue with it on source map support.

Conceptually you should not use gulp-cache to gulp-typescript. Because typescript transpiling is NOT one-to-one transform. When compiling one ts file, the TypeScript compiler does typing checking across the whole project. So even when the file being processing is not changed, it could pass or fail due to changes from other files.
